rx_fifo_depth    CV4Pai0wkpnN5s4jbmTL5BJ0MvwMXOca
tx_fifo_depth    kupB5gWF1ZvIviPr46TohEFo1Tawv0dH
ic_tx_abrt_source_en    UR9bHfgx2IMXeQYXIr5Pczt5EZx5NFKj
wr_en_int    xvMteNaT9ZCldw0cA829poSeByqN5MT4
reg_wr_en    Muoh0UWoZgIdNJ2jRii7w4FzJXfkYSXz
reg_rd_en    algxT8gEI6MeVjoGDdo3LjOA0LkAJWQ1
ic_con_en    lKUdOKeIYzUMI14P7qRe8cX7tbgpDQ20
ic_con_we    gW3YLNX5H0ljahHJPzX59dCMgRW8KcTw
ic_tar_en    sKty0eCaiNxNIMi5CdFana3TOFm7kvdc
ic_tar_we    AzvI3z8g2Mw2DezPXQMUdXfMtmWGWA3u
ic_sar_en    C4P7DrK3qy3I4PcrpwKjfpuW68nIqQni
ic_sar_we    SdFz0yT3JUnjvzikVTmIGafMDZa5XFV9
ic_hs_maddr_en    etIFG9vyPZPVrQcyogr0J3V9YilDpVU2
ic_hs_maddr_we    qjYGNhm09B7HkFNmJhvNTtW7zyGu87lD
ic_data_cmd_en    Mkg90fHkBKpMM42yyNt2SbQ7fPx54SuM
ic_data_cmd_we    fQmBPCoh7BqVlAUQIdhGIdPpyJl6fIQ1
ic_ss_hcnt_en    TK7JMVvRieIyW9cJLeoRuc87HTcZCdbe
ic_ss_lcnt_en    H5OiNWWBPJRDfbgXznV73a2cDQgsMyJK
ic_fs_hcnt_en    Ns7M8ScppLUcSHUceapXHfWancX4iHSX
ic_fs_lcnt_en    xNMRUx5VtEICItFVHmg01PmkE3kKx02x
ic_hs_hcnt_en    p5XBuStaD3OR4T0LwewVl0724CuEU0mM
ic_hs_lcnt_en    H9w9ncIjfS0EdBLwpJIgRlQtggNhoxq0
ic_ss_hcnt_we    mUqNU2UX2LsVlGhCGqQRCVpaFPevwswB
ic_ss_lcnt_we    WRq8ExutqNzZsonqQrIHNP4Q64sc0Zva
ic_fs_hcnt_we    iKEH4S8fZcsVdb8rxM2xqbx19tQWbw9W
ic_fs_lcnt_we    uz6yie5xHcmUzlSiCD7Be2kImrtKnPIv
ic_hs_hcnt_we    tKsafMJIsbgugvXbKiQB78x6EH5XpIvJ
ic_hs_lcnt_we    iVheBNk53JDsUjp2xTaD9QWEwePGC9jl
ic_fs_spklen_en    dcl6VblBEcaw0cHdOxPyGDDmwh4POYWV
ic_fs_spklen_we    Npr1gKFaeNewe49k91WHAqjTrTdt3RyV
ic_hs_spklen_en    TuPWRYd2zsoaDVFReJX8gPQPlVpIxRFn
ic_hs_spklen_we    hBSG635By2bnLx3qDjo94pYFKw3WEvpR
ic_intr_stat_en    Hi95hG5OsI136TpVcUs5QvlApUSHqsKM
ic_intr_mask_en    XzTCzrAQDBWKKLAckoRUe910faC7T6dA
ic_intr_mask_we    PY3OscmSLt5khMePqlF30HOA3TwCYRQw
ic_raw_intr_stat_en    Vi5XX7BBRlfr7oxJxRr3Wryo8kDcsKCH
ic_rx_tl_en    nyg5OF4ocwIRsXWKZfcI3po33EfxtsD2
ic_rx_tl_we    lpslUOZCAOgVbxwyUR0vIrfv6OCXFgye
ic_tx_tl_en    WuGSGglOmbuNaaM6iQAuEbdS2ww71KJQ
ic_tx_tl_we    R5w6P8lJNiAANzKBDwQk1NSBPXe3HfIs
ic_enable_en    oyfMwVL1BlpyhN1AR3xD36e1b1rj5uJE
ic_enable_we    Fctgn05ONv0dvTEhAbkLPsXe1g5jfJfp
ic_status_en    TjRu0RFvqEishC4VaoqJB2hJIboas4cb
ic_txflr_en    X53Ebrn1zZqWavEMZeyvsrujeD5OvTOn
ic_rxflr_en    LAlV8t72YDiKeRZJQMdcRsepexWI1ubq
ic_comp_param_1_en    w7UFEZOsn29PJN06SHp3nyT8mFZaoPAe
ic_comp_version_en    Jmyrc99pg4M7v6ZqCzlUI7KJH29pzABM
ic_comp_type_en    fxRJv6eNDrS3wTTI23uhLEdUdibVZOHX
ic_sda_setup_en    Ais1Hp7y8989tdvXFRdfrnavrt3wVrIy
ic_sda_setup_we    QjEPuYuZfSFyetHJZD9ltPf76uozSO5C
ic_ack_general_call_en    mDA3BH1LmvBQPd5dLHNEWtm0pmniQTOw
ic_ack_general_call_we    j0Llez3D7nmARw9mvL2k2KMC1zTiK7fI
ic_enable_status_en    GN3e9VCdkNdFNYhZfKf5ZCfm05rpwDZs
ic_enable_status    REwYyMTwcAgMNttByLCqpdxmepFoE0cw
ic_sda_hold_en    J3M3ef8A5cmKTXjCMXIkkJr3kN4HkINf
ic_sda_hold_we    TEhHBRbJkTuYpieKo7lT1qq19EKKqSjY
ic_comp_param_1    EyBjfxBVvij4BNKOqMI23jcWlQMW4bl8
ic_comp_version    nrclwVMJNVX337CAlnNp9ftIEKKLGQzN
ic_comp_type    gXk4VC9FLlEER1pyrdOcBf6U1JQjFvCn
speed    BWIXiFHqcCdCdKMUooDP82PUrcNM9Dj8
ic_status    mtAyx6YS8Z99BaiDIh0PftzbiGmfVSm0
ic_con    VkDhoPhyi1GbqmFHi7zNOAPT8sWdP1vz
ic_con_pre    v7lxJHhPSHcMd64F5yP6Fn8jriMtVwuU
ic_tar_reg    wz3BZygJitPVyF6vh1TYwgz7ldwxZyVw
r_ic_ss_hcnt    wrH6KPHWdviDtrv9MmgEjWDKeSzc9hXl
r_ic_ss_lcnt    DH30AVNd4BOqbch028M0MqAKfY308w8h
r_ic_fs_hcnt    rss9B9ApfzTyISeKxzUkZi1rGHTtFgqk
r_ic_fs_lcnt    WQPEr2r7In1qW5obB5nX3PgGCI63pBfo
r_ic_hs_hcnt    fjKmB142KYzOm9KgafhylvZd8QlCUG7x
r_ic_hs_lcnt    UDDrSGqzfY2xQceXYOpjeyXlbky4GUvC
r_ic_fs_spklen    imuGmFkz3J9RyAG5IBkFRIgiVMUtkn6e
r_ic_hs_spklen    nMvleKjzHT7ooQfQKweJfBt9ciijZOQT
hcr_ic_ss_hcnt    XeevtxZQdrlWq59kAJpK4tzgtomxJd4D
hcr_ic_ss_lcnt    mLaYpkZ1ZAmQZ31tWiPnjDHb6xJxUCkx
hcr_ic_fs_hcnt    dmW36FS9ErVYmRWYSltETrLo6GiojaM6
hcr_ic_fs_lcnt    Wmu4GoXpvQOYKlxKx3CHaMHge2eHSdPR
hcr_ic_hs_hcnt    xEWRHhGddmM3WC1ExtifdJN9kyhfR3Ic
hcr_ic_hs_lcnt    ulbLq7bDke6iG6WYWL513JAAxyzuoPQp
ic_ss_hcnt    flGZubqArpJlNgysEkma8CjYYaTPB8om
ic_ss_lcnt    yT86aafPwFO3Oj9BufLJUssnBKRbBKDN
ic_hs_hcnt    ka7ahdQtyPZXbFXJR6zRout97UoYhFIW
ic_hs_lcnt    Rqot9zc8gd7vgt2T0izzPht3X81qQwo5
fix_a    wjjVxZ4h1nphSRZqULVmoGA5sXL7PlPd
fix_b    VZEXJ6ENZOrOWm15hup0DqbwnFtxwRne
fix_c    yaLerXWIOgSOZ2Blo4roJ9AQGvI9PuTK
fifo_rst_n_int    izNFcfELEMNKe3sMj9JAO8cTwIC6xcQc
ic_enable_reg    CoU4o8jtni5ibD75iHJLPafLSA8fRtZB
ic_txflr    anjLlAFUIU1dlKu5E5NkouRfALeokWMq
ic_txflr_flushed    H3w8sSYtr91romkcf1zDBemIPi6UO50y
ic_rxflr    sV2ht7fgE2jDVhwveJg9aaKaNbckZITm
dr_ir    EM4ixpyNS9bw9JjAlurMmgqUwDlQ73kK
ic_rx_tl    K7pJhsBnqzZBE5Hjiz1gNiQAzKPgaohJ
activity_r    SWBXRLCTkeWPf0GKOZhjrVM2PYgS7mhQ
mst_activity_r    ZHRMXxPywAMbivARE6YwrQHaNBTEq99L
slv_activity_r    zYbD5A1iIoUVdd1g2o58X7H4QbfhCcxa
ic_tar_int    c5ZfzhYJwj0UyJVddOwo62rvWXAAJ6SE
ic_sar_int    edk3o2CMnSF6kIo70AVsMEQRUCuozM12
dr_ir_int    XbYqv3jiuOwsPONZ5AdJHisfjIrJxnW2
ic_intr_mask_int    VsKF1GGMYxNqQvpSdkMdDhg3Fs3ofSiv
ic_sda_hold_int    D1x4oyNVNylLSyJrJc0wl9goBim5Vcfo
